name: Run

on:
  watch:
    types: [started]
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
